# Generated by Django 5.1.2 on 2024-12-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='zamrznuti_balans',
            field=models.FloatField(default=0.0),
        ),
    ]
