# Generated by Django 5.1.2 on 2024-12-06 21:08

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_korisnik_zamrznuti_balans'),
    ]

    operations = [
        migrations.AddField(
            model_name='aukcija',
            name='kreirao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='database.korisnik'),
        ),
        migrations.AddField(
            model_name='aukcija',
            name='slika',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='Slika',
        ),
    ]
