# Generated by Django 5.1.2 on 2025-01-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_aukcija_kreirao_aukcija_slika_delete_slika'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
