# Generated by Django 5.1.2 on 2025-01-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_korisnik_is_active_korisnik_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='korisnik',
            name='is_authenticated',
            field=models.BooleanField(default=True),
        ),
    ]
